/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.tcc.view;

import br.com.tcc.entity.Acesso;
import br.com.tcc.util.EntityManagerUtil;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author Leonardo
 */
public class ControleAcessosView extends javax.swing.JFrame {

    /**
     * Creates new form ControleAcessosView
     */
    public ControleAcessosView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = EntityManagerUtil.getEntityManager();
        funcionarioQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT f FROM Funcionario f");
        funcionarioList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(funcionarioQuery.getResultList());
        AgroEmpresarialPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("AgroEmpresarialPU").createEntityManager();
        acessoQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT a FROM Acesso a");
        acessoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(acessoQuery.getResultList());
        jScrollPane1 = new javax.swing.JScrollPane();
        DefaultMutableTreeNode pai = new DefaultMutableTreeNode("AgroEmpresarial");

        DefaultMutableTreeNode filho1 = new DefaultMutableTreeNode("Manutenção");
        pai.add(filho1);

        DefaultMutableTreeNode neto1 = new DefaultMutableTreeNode("Bairro");
        filho1.add(neto1);
        DefaultMutableTreeNode neto2 = new DefaultMutableTreeNode("Cidade");
        filho1.add(neto2);
        DefaultMutableTreeNode neto3 = new DefaultMutableTreeNode("Cliente");
        filho1.add(neto3);

        DefaultMutableTreeNode neto4 = new DefaultMutableTreeNode("Fornecedor");
        filho1.add(neto4);
        DefaultMutableTreeNode neto5 = new DefaultMutableTreeNode("Função");
        filho1.add(neto5);
        DefaultMutableTreeNode neto6 = new DefaultMutableTreeNode("Funcionário");
        filho1.add(neto6);

        DefaultMutableTreeNode neto7 = new DefaultMutableTreeNode("Produto");
        filho1.add(neto7);
        DefaultMutableTreeNode neto8 = new DefaultMutableTreeNode("Tipo Fornecedor");
        filho1.add(neto8);
        DefaultMutableTreeNode neto9 = new DefaultMutableTreeNode("Tipo Pagamento");
        filho1.add(neto9);
        DefaultMutableTreeNode neto10 = new DefaultMutableTreeNode("Unidade");
        filho1.add(neto10);

        DefaultMutableTreeNode filho2 = new DefaultMutableTreeNode("Outros");
        pai.add(filho2);

        DefaultMutableTreeNode neto11 = new DefaultMutableTreeNode("Controle de Acesso");
        filho2.add(neto11);
        DefaultMutableTreeNode neto12 = new DefaultMutableTreeNode("Pedido");
        filho2.add(neto12);
        DefaultMutableTreeNode neto13 = new DefaultMutableTreeNode("Entrada");
        filho2.add(neto13);
        DefaultMutableTreeNode neto14 = new DefaultMutableTreeNode("Contas a receber");
        filho2.add(neto14);

        DefaultMutableTreeNode filho3 = new DefaultMutableTreeNode("Relatórios");
        pai.add(filho3);

        DefaultMutableTreeNode neto15 = new DefaultMutableTreeNode("Produto");
        filho3.add(neto15);
        DefaultMutableTreeNode neto16 = new DefaultMutableTreeNode("Mais Vendidos");
        filho3.add(neto16);
        DefaultMutableTreeNode neto17 = new DefaultMutableTreeNode("Vendas do dia");
        filho3.add(neto17);

        DefaultMutableTreeNode filho4 = new DefaultMutableTreeNode("Apurar vendas");
        filho3.add(filho4);

        DefaultMutableTreeNode neto18 = new DefaultMutableTreeNode("Diario");
        filho4.add(neto18);
        DefaultMutableTreeNode neto19 = new DefaultMutableTreeNode("Mensal");
        filho4.add(neto19);
        DefaultMutableTreeNode neto20 = new DefaultMutableTreeNode("Anual");
        filho4.add(neto20);

        DefaultMutableTreeNode neto21 = new DefaultMutableTreeNode("Balanço Anual");
        filho3.add(neto21);
        DefaultMutableTreeNode neto22 = new DefaultMutableTreeNode("Pesquisa Venda");
        filho3.add(neto22);

        DefaultMutableTreeNode filho5 = new DefaultMutableTreeNode("Gráficos");
        pai.add(filho5);
        DefaultMutableTreeNode filho6 = new DefaultMutableTreeNode("Mais vendidos");
        filho5.add(filho6);

        DefaultMutableTreeNode neto23 = new DefaultMutableTreeNode("Pizza");
        filho6.add(neto23);
        DefaultMutableTreeNode neto24 = new DefaultMutableTreeNode("Linha");
        filho6.add(neto24);
        DefaultMutableTreeNode neto25 = new DefaultMutableTreeNode("Barras");
        filho6.add(neto25);
        DefaultMutableTreeNode neto26 = new DefaultMutableTreeNode("Área");
        filho6.add(neto26);
        DefaultMutableTreeNode filho7 = new DefaultMutableTreeNode("Apurar Vendas");
        filho5.add(filho7);
        DefaultMutableTreeNode filho8 = new DefaultMutableTreeNode("Mensal");
        filho7.add(filho8);
        DefaultMutableTreeNode neto27 = new DefaultMutableTreeNode("Pizza");
        filho8.add(neto27);
        DefaultMutableTreeNode filho9 = new DefaultMutableTreeNode("Anual");
        filho7.add(filho9);
        DefaultMutableTreeNode neto28 = new DefaultMutableTreeNode("Barras");
        filho9.add(neto28);
        DefaultMutableTreeNode filho10 = new DefaultMutableTreeNode("Comparativos");
        filho5.add(filho10);
        DefaultMutableTreeNode neto29 = new DefaultMutableTreeNode("Valores Anual");
        filho10.add(neto29);
        DefaultMutableTreeNode neto30 = new DefaultMutableTreeNode("Valores por Epocas");
        filho10.add(neto30);
        DefaultMutableTreeNode neto31 = new DefaultMutableTreeNode("Entrada e Saída");
        filho5.add(neto31);
        jTree1 = new javax.swing.JTree(pai);
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFuncionario = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblAcesso = new javax.swing.JTable();
        btnConceder = new javax.swing.JButton();
        btnRetirar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle de Acesso");

        jScrollPane1.setViewportView(jTree1);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, funcionarioList, tblFuncionario);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${login}"));
        columnBinding.setColumnName("Login");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane2.setViewportView(tblFuncionario);

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, acessoList, tblAcesso);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Código");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idFuncionario}"));
        columnBinding.setColumnName("Funcionario");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${modelo}"));
        columnBinding.setColumnName("Modelo");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane3.setViewportView(tblAcesso);

        btnConceder.setText("Conceder");
        btnConceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcederActionPerformed(evt);
            }
        });

        btnRetirar.setText("Retirar");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConceder)
                        .addGap(18, 18, 18)
                        .addComponent(btnRetirar)
                        .addGap(18, 18, 18)
                        .addComponent(btnFechar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConceder)
                            .addComponent(btnRetirar)
                            .addComponent(btnFechar)
                            .addComponent(btnSalvar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param evt concede permissão ao funcionário
     */
    private void btnConcederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcederActionPerformed
        Acesso ne = new Acesso();

        int index = tblFuncionario.getSelectedRow();
        ne.setIdFuncionario(funcionarioList.get(index).getId());
        ne.setModelo(jTree1.getLastSelectedPathComponent().toString());
        entityManager.persist(ne);
        acessoList.add(ne);

    }//GEN-LAST:event_btnConcederActionPerformed
/**
 * 
 * @param evt retira permissão do usuário 
 */
    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        try {
            int index = tblAcesso.getSelectedRow();
            acessoList.remove(index);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao Retirar Acesso \n" + e.getMessage());
        }
    }//GEN-LAST:event_btnRetirarActionPerformed
/**
 * 
 * @param evt responsável por salvar alteração de permissões  
 */
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            entityManager.getTransaction().begin();
            entityManager.getTransaction().commit();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao Gravar \n" + e.getMessage());
        }

//        try {
//                Acesso obj = acessoList.get(linhaClicada);
//                entityManager.getTransaction().begin();
//                entityManager.getTransaction().commit();
//                entityManager.persist(ne);
//                entityManager.getTransaction().begin();
//            } catch (Exception e) {
//                e.printStackTrace();
//            }
    }//GEN-LAST:event_btnSalvarActionPerformed
/**
 * 
 * @param evt evento para fechar a janela de controle de acesso 
 */
    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        dispose();
    }//GEN-LAST:event_btnFecharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager AgroEmpresarialPUEntityManager;
    private java.util.List<br.com.tcc.entity.Acesso> acessoList;
    private javax.persistence.Query acessoQuery;
    private javax.swing.JButton btnConceder;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JButton btnSalvar;
    private javax.persistence.EntityManager entityManager;
    private java.util.List<br.com.tcc.entity.Funcionario> funcionarioList;
    private javax.persistence.Query funcionarioQuery;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTree jTree1;
    private javax.swing.JTable tblAcesso;
    private javax.swing.JTable tblFuncionario;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
