/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.tcc.view;

import br.com.tcc.Comparativo.ConsultarVendasGrafico;
import br.com.tcc.Comparativo.VendaAnualComparativo;
import br.com.tcc.GraficoTop10.GraficoBarra;
import br.com.tcc.GraficoTop10.GraficoLinha;
import br.com.tcc.GraficoTop10.GraficoOnda;
import br.com.tcc.GraficoTop10.GraficoPizza;
import br.com.tcc.entity.Acesso;
import br.com.tcc.entity.Funcionario;
import br.com.tcc.graficoFinanceiro.ComparaçãoMensalBarraLinha;
import br.com.tcc.graficoFinanceiro.VendasAnuallBarra;
import br.com.tcc.graficoFinanceiro.VendasMensalPizza;
import br.com.tcc.relat.BalancoAnual;
import br.com.tcc.relat.ConsultarVendas;
import br.com.tcc.relat.MaisVendidos;
import br.com.tcc.relat.ProdutosRelat;
import br.com.tcc.relat.VendasDoAno;
import br.com.tcc.relat.VendasDoDia;
import br.com.tcc.relat.VendasDoDiaValores;
import br.com.tcc.relat.VendasDoMes;
import br.com.tcc.util.Data;
import br.com.tcc.util.EncriptaSenha;
import br.com.tcc.util.EntityManagerUtil;
import static br.com.tcc.view.LoginView.txtLogin;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.Query;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Leonardo
 */
public class MenuPrincipalView extends javax.swing.JFrame {

    Data mostra_data;

    /**
     * Construtor padrão da classe <b>Menu Principal</b>
     *
     * inicializa mostraDara starta a theeds para atualizar as horas mostra data
     * e horas na tela
     */
    public MenuPrincipalView() {
        this.setExtendedState(MAXIMIZED_BOTH);
        initComponents();
        mostra_data = new Data();
        mostra_data.le_data();
        txtSemana.setText(mostra_data.dia_semana);
        txtSemana.setFont(new java.awt.Font("Tahoma", 0, 24));
        txtData.setText("Data: " + mostra_data.dia + "/" + mostra_data.mes + "/" + mostra_data.ano);
        txtData.setFont(new java.awt.Font("Tahoma", 0, 24));
        mostra_data.le_hora();
        //horas.start();
        txtLogou.setText("Entrou as : " + mostra_data.hora);
        txtLogou.setFont(new java.awt.Font("Tahoma", 0, 24));
        txtNomeUsuario.setText(txtLogin.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = EntityManagerUtil.getEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT f FROM Funcionario f");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        queryAcesso = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT a FROM Acesso a");
        listAcesso = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : queryAcesso.getResultList();
        vendaDetalheQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT pd FROM Vendadetalhe pd");
        vendaDetalheList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(vendaDetalheQuery.getResultList());
        produtoQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Produto p");
        produtoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(produtoQuery.getResultList());
        pnlAcoes = new javax.swing.JPanel();
        btnCadastroUsuario = new javax.swing.JButton();
        btnEfetuaVenda = new javax.swing.JButton();
        btnConsulta = new javax.swing.JButton();
        btnEfetuaOrcamento = new javax.swing.JButton();
        pnlInformacao = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtSejaBemVindo = new javax.swing.JLabel();
        txtNomeUsuario = new javax.swing.JLabel();
        txtData = new javax.swing.JLabel();
        txtHora = new javax.swing.JLabel();
        txtSemana = new javax.swing.JLabel();
        txtLogou = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JLabel();
        barraMenuPrincipal = new javax.swing.JMenuBar();
        menuManutenção = new javax.swing.JMenu();
        itemMenuBairro = new javax.swing.JMenuItem();
        itemMenuCidade = new javax.swing.JMenuItem();
        itemMenuCliente = new javax.swing.JMenuItem();
        itemMenuFornecedor = new javax.swing.JMenuItem();
        itemMenuFuncao = new javax.swing.JMenuItem();
        itemMenuFuncionario = new javax.swing.JMenuItem();
        itemMenuProduto = new javax.swing.JMenuItem();
        itemMenuTipoFornecedor = new javax.swing.JMenuItem();
        itemMenuTipoPagamento = new javax.swing.JMenuItem();
        itemMenuUnidade = new javax.swing.JMenuItem();
        menuOutros = new javax.swing.JMenu();
        itemMenuControleAcesso = new javax.swing.JMenuItem();
        itemMenuPedido = new javax.swing.JMenuItem();
        itemMenuEntrada = new javax.swing.JMenuItem();
        itemMenuContaReceber = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        relatProduto = new javax.swing.JMenuItem();
        relatMaisVendido = new javax.swing.JMenuItem();
        RelatVendaDia = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemMenuDiario = new javax.swing.JMenuItem();
        itemMenuMensal = new javax.swing.JMenuItem();
        itemMenuAnual = new javax.swing.JMenuItem();
        itemMenuBalanco = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        itemMenuPizza = new javax.swing.JMenuItem();
        itemMenuLinha = new javax.swing.JMenuItem();
        itemMenuBarras = new javax.swing.JMenuItem();
        itemMenuOndas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        diarioPizza = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        anualBarra = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        itemMenuValorAnual = new javax.swing.JMenuItem();
        itemMenuEpoca = new javax.swing.JMenuItem();
        itemMenuEntradaSaida = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        pnlAcoes.setLayout(new java.awt.GridLayout(1, 0));

        btnCadastroUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/tcc/imagem/cliente.png"))); // NOI18N
        btnCadastroUsuario.setToolTipText("Cadastros de Cliente");
        btnCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroUsuarioActionPerformed(evt);
            }
        });
        pnlAcoes.add(btnCadastroUsuario);

        btnEfetuaVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/tcc/imagem/ico-ecommerce.png"))); // NOI18N
        btnEfetuaVenda.setToolTipText("Efetuar Venda");
        btnEfetuaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEfetuaVendaActionPerformed(evt);
            }
        });
        pnlAcoes.add(btnEfetuaVenda);

        btnConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/tcc/imagem/consulta.png"))); // NOI18N
        btnConsulta.setToolTipText("Consultar");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });
        pnlAcoes.add(btnConsulta);

        btnEfetuaOrcamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/tcc/imagem/orcamento.png"))); // NOI18N
        btnEfetuaOrcamento.setToolTipText("Efetuar Orçamento");
        btnEfetuaOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEfetuaOrcamentoActionPerformed(evt);
            }
        });
        pnlAcoes.add(btnEfetuaOrcamento);

        pnlInformacao.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Informações"));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtSejaBemVindo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSejaBemVindo.setText("Seja bem-vindo");

        txtNomeUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtNomeUsuario.setText("USUARIO");

        txtData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtData.setText("Data: ");

        txtHora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtHora.setText("Hora:");

        txtSemana.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSemana.setText("Semana");

        txtLogou.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLogou.setText("Entrou as:");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Horário de trabalho"));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("14h00 às 18h00");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("08:00 às 12h00");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Manhã:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Tarde:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtSejaBemVindo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomeUsuario))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtData)
                            .addComponent(txtHora)
                            .addComponent(txtLogou))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(txtSemana)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSejaBemVindo)
                    .addComponent(txtNomeUsuario))
                .addGap(35, 35, 35)
                .addComponent(txtSemana)
                .addGap(24, 24, 24)
                .addComponent(txtData)
                .addGap(26, 26, 26)
                .addComponent(txtHora)
                .addGap(18, 18, 18)
                .addComponent(txtLogou)
                .addGap(33, 33, 33)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtUsuario.setText("jLabel5");

        javax.swing.GroupLayout pnlInformacaoLayout = new javax.swing.GroupLayout(pnlInformacao);
        pnlInformacao.setLayout(pnlInformacaoLayout);
        pnlInformacaoLayout.setHorizontalGroup(
            pnlInformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214)
                .addComponent(txtUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInformacaoLayout.setVerticalGroup(
            pnlInformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlInformacaoLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(txtUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuManutenção.setText("Manutenção");

        itemMenuBairro.setText("Bairro");
        itemMenuBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuBairroActionPerformed(evt);
            }
        });
        menuManutenção.add(itemMenuBairro);

        itemMenuCidade.setText("Cidade");
        itemMenuCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCidadeActionPerformed(evt);
            }
        });
        menuManutenção.add(itemMenuCidade);

        itemMenuCliente.setText("Cliente");
        itemMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuClienteActionPerformed(evt);
            }
        });
        menuManutenção.add(itemMenuCliente);

        itemMenuFornecedor.setText("Fornecedor");
        itemMenuFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuFornecedorActionPerformed(evt);
            }
        });
        menuManutenção.add(itemMenuFornecedor);

        itemMenuFuncao.setText("Função");
        itemMenuFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuFuncaoActionPerformed(evt);
            }
        });
        menuManutenção.add(itemMenuFuncao);

        itemMenuFuncionario.setText("Funcionário");
        itemMenuFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuFuncionarioActionPerformed(evt);
            }
        });
        menuManutenção.add(itemMenuFuncionario);

        itemMenuProduto.setText("Produto");
        itemMenuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuProdutoActionPerformed(evt);
            }
        });
        menuManutenção.add(itemMenuProduto);

        itemMenuTipoFornecedor.setText("Tipo Fornecedor");
        itemMenuTipoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuTipoFornecedorActionPerformed(evt);
            }
        });
        menuManutenção.add(itemMenuTipoFornecedor);

        itemMenuTipoPagamento.setText("Tipo Pagamento");
        itemMenuTipoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuTipoPagamentoActionPerformed(evt);
            }
        });
        menuManutenção.add(itemMenuTipoPagamento);

        itemMenuUnidade.setText("Unidade");
        itemMenuUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuUnidadeActionPerformed(evt);
            }
        });
        menuManutenção.add(itemMenuUnidade);

        barraMenuPrincipal.add(menuManutenção);

        menuOutros.setText("Outros");

        itemMenuControleAcesso.setText("Controle de Acesso");
        itemMenuControleAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuControleAcessoActionPerformed(evt);
            }
        });
        menuOutros.add(itemMenuControleAcesso);

        itemMenuPedido.setText("Pedido");
        itemMenuPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuPedidoActionPerformed(evt);
            }
        });
        menuOutros.add(itemMenuPedido);

        itemMenuEntrada.setText("Entrada");
        itemMenuEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuEntradaActionPerformed(evt);
            }
        });
        menuOutros.add(itemMenuEntrada);

        itemMenuContaReceber.setText("Contas a receber");
        itemMenuContaReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuContaReceberActionPerformed(evt);
            }
        });
        menuOutros.add(itemMenuContaReceber);

        barraMenuPrincipal.add(menuOutros);

        menuRelatorio.setText("Relatórios");

        relatProduto.setText("Produto");
        relatProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatProdutoActionPerformed(evt);
            }
        });
        menuRelatorio.add(relatProduto);

        relatMaisVendido.setText("Mais Vendido");
        relatMaisVendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatMaisVendidoActionPerformed(evt);
            }
        });
        menuRelatorio.add(relatMaisVendido);

        RelatVendaDia.setText("Vendas do dia");
        RelatVendaDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatVendaDiaActionPerformed(evt);
            }
        });
        menuRelatorio.add(RelatVendaDia);

        jMenu3.setText("Apurar vendas");

        itemMenuDiario.setText("Diario");
        itemMenuDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuDiarioActionPerformed(evt);
            }
        });
        jMenu3.add(itemMenuDiario);

        itemMenuMensal.setText("Mensal");
        itemMenuMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuMensalActionPerformed(evt);
            }
        });
        jMenu3.add(itemMenuMensal);

        itemMenuAnual.setText("Anual");
        itemMenuAnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuAnualActionPerformed(evt);
            }
        });
        jMenu3.add(itemMenuAnual);

        menuRelatorio.add(jMenu3);

        itemMenuBalanco.setText("Balanço Anual");
        itemMenuBalanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuBalancoActionPerformed(evt);
            }
        });
        menuRelatorio.add(itemMenuBalanco);

        jMenuItem1.setText("Pesquisa venda");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuRelatorio.add(jMenuItem1);

        barraMenuPrincipal.add(menuRelatorio);

        jMenu1.setText("Gráficos");

        jMenu2.setText("Mais vendidos");

        itemMenuPizza.setText("Pizza");
        itemMenuPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuPizzaActionPerformed(evt);
            }
        });
        jMenu2.add(itemMenuPizza);

        itemMenuLinha.setText("Linha");
        itemMenuLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuLinhaActionPerformed(evt);
            }
        });
        jMenu2.add(itemMenuLinha);

        itemMenuBarras.setText("Barras");
        itemMenuBarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuBarrasActionPerformed(evt);
            }
        });
        jMenu2.add(itemMenuBarras);

        itemMenuOndas.setText("Área");
        itemMenuOndas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuOndasActionPerformed(evt);
            }
        });
        jMenu2.add(itemMenuOndas);

        jMenu1.add(jMenu2);

        jMenu4.setText("Apurar Vendas");

        jMenu6.setText("Mensal");

        diarioPizza.setText("Pizza");
        diarioPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diarioPizzaActionPerformed(evt);
            }
        });
        jMenu6.add(diarioPizza);

        jMenu4.add(jMenu6);

        jMenu7.setText("Anual");

        anualBarra.setText("Barras");
        anualBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anualBarraActionPerformed(evt);
            }
        });
        jMenu7.add(anualBarra);

        jMenu4.add(jMenu7);

        jMenu1.add(jMenu4);

        jMenu8.setText("Comparativos");

        itemMenuValorAnual.setText("Valores Anual");
        itemMenuValorAnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuValorAnualActionPerformed(evt);
            }
        });
        jMenu8.add(itemMenuValorAnual);

        itemMenuEpoca.setText("Valores por Epocas");
        itemMenuEpoca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuEpocaActionPerformed(evt);
            }
        });
        jMenu8.add(itemMenuEpoca);

        jMenu1.add(jMenu8);

        itemMenuEntradaSaida.setText("Entrada e Saída");
        itemMenuEntradaSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuEntradaSaidaActionPerformed(evt);
            }
        });
        jMenu1.add(itemMenuEntradaSaida);

        barraMenuPrincipal.add(jMenu1);

        menuSair.setText("Sair");
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        barraMenuPrincipal.add(menuSair);

        setJMenuBar(barraMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(pnlAcoes, javax.swing.GroupLayout.DEFAULT_SIZE, 981, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlInformacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlInformacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     *
     * @param evt responsável por executar a classe BairroView
     */
    private void itemMenuBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuBairroActionPerformed
        if (verificaAcesso(itemMenuBairro.getText(), txtNomeUsuario.getText())) {
            JFrame form = new BairroView();
            form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            form.setLocationRelativeTo(null);
            form.setResizable(false);
            form.setVisible(true);
            new BairroView();
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem acesso ao módulo");
        }
    }//GEN-LAST:event_itemMenuBairroActionPerformed
    /**
     *
     * @param evt responsável por executar a classe CidadeView
     */
    private void itemMenuCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCidadeActionPerformed
        if (verificaAcesso(itemMenuCidade.getText(), txtNomeUsuario.getText())) {
            JFrame form = new CidadeView();
            form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            form.setLocationRelativeTo(null);
            form.setResizable(false);
            form.setVisible(true);
            new CidadeView();
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem acesso ao módulo");
        }
    }//GEN-LAST:event_itemMenuCidadeActionPerformed
    /**
     *
     * @param evt responsável por fechar o sistema
     */
    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_menuSairMouseClicked
    /**
     *
     * @param evt responsável por executar a classe ClienteView
     */
    private void itemMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuClienteActionPerformed
        if (verificaAcesso(itemMenuCliente.getText(), txtNomeUsuario.getText())) {
            JFrame form = new ClienteView();
            form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            form.setLocationRelativeTo(null);
            form.setResizable(false);
            form.setVisible(true);
            new ClienteView();
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem acesso ao módulo");
        }
    }//GEN-LAST:event_itemMenuClienteActionPerformed
    /**
     *
     * @param evt responsável por executar a classe FornecedorView
     */
    private void itemMenuFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuFornecedorActionPerformed
        if (verificaAcesso(itemMenuFornecedor.getText(), txtNomeUsuario.getText())) {
            JFrame form = new FornecedorView();
            form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            form.setLocationRelativeTo(null);
            form.setResizable(false);
            form.setVisible(true);
            new FornecedorView();
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem acesso ao módulo");
        }
    }//GEN-LAST:event_itemMenuFornecedorActionPerformed

    /**
     *
     * @param evt responsável por executar a classe FuncaoView
     */
    private void itemMenuFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuFuncaoActionPerformed
        if (verificaAcesso(itemMenuFuncao.getText(), txtNomeUsuario.getText())) {
            JFrame form = new FuncaoView();
            form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            form.setLocationRelativeTo(null);
            form.setResizable(false);
            form.setVisible(true);
            new FuncaoView();
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem acesso ao módulo");
        }
    }//GEN-LAST:event_itemMenuFuncaoActionPerformed
    /**
     *
     * @param evt responsável por executar a classe FuncionárioView
     */
    private void itemMenuFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuFuncionarioActionPerformed
        if (verificaAcesso(itemMenuFuncionario.getText(), txtNomeUsuario.getText())) {
            JFrame form = new FuncionarioView();
            form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            form.setLocationRelativeTo(null);
            form.setResizable(false);
            form.setVisible(true);
            new FuncionarioView();
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem acesso ao módulo");
        }
    }//GEN-LAST:event_itemMenuFuncionarioActionPerformed
    /**
     *
     * @param evt responsável por executar a classe ProdutoView
     */
    private void itemMenuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuProdutoActionPerformed
        if (verificaAcesso(itemMenuProduto.getText(), txtNomeUsuario.getText())) {
            JFrame form = new ProdutoView();
            form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            form.setLocationRelativeTo(null);
            form.setResizable(false);
            form.setVisible(true);
            new ProdutoView();
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem acesso ao módulo");
        }
    }//GEN-LAST:event_itemMenuProdutoActionPerformed
    /**
     *
     * @param evt responsável por executar a classe TipoFornecedorView
     */
    private void itemMenuTipoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuTipoFornecedorActionPerformed
        if (verificaAcesso(itemMenuTipoFornecedor.getText(), txtNomeUsuario.getText())) {
            JFrame form = new TipoFornecedorView();
            form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            form.setLocationRelativeTo(null);
            form.setResizable(false);
            form.setVisible(true);
            new TipoFornecedorView();
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem acesso ao módulo");
        }
    }//GEN-LAST:event_itemMenuTipoFornecedorActionPerformed
    /**
     *
     * @param evt responsável por executar a classe TipoPagamentoView
     */
    private void itemMenuTipoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuTipoPagamentoActionPerformed
        if (verificaAcesso(itemMenuTipoPagamento.getText(), txtNomeUsuario.getText())) {
            JFrame form = new TipoPagamentoView();
            form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            form.setLocationRelativeTo(null);
            form.setResizable(false);
            form.setVisible(true);
            new TipoPagamentoView();
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem acesso ao módulo");
        }
    }//GEN-LAST:event_itemMenuTipoPagamentoActionPerformed
    /**
     *
     * @param evt responsável por executar a classe UnidadeView
     */
    private void itemMenuUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuUnidadeActionPerformed
        if (verificaAcesso(itemMenuUnidade.getText(), txtNomeUsuario.getText())) {
            JFrame form = new UnidadeView();
            form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            form.setLocationRelativeTo(null);
            form.setResizable(false);
            form.setVisible(true);
            new UnidadeView();
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem acesso ao módulo");
        }
    }//GEN-LAST:event_itemMenuUnidadeActionPerformed
    /**
     *
     * @param evt responsável por executar a classe ClienteFuncionarioView
     */
    private void btnCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroUsuarioActionPerformed
        JFrame form = new ClienteFuncionarioView();
        form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);
        new ClienteFuncionarioView();
    }//GEN-LAST:event_btnCadastroUsuarioActionPerformed
    /**
     *
     * @param evt responsável por setar as data/hora no painel de informações
     */
    private void horasOnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horasOnTime

        mostra_data.le_hora();
        txtHora.setText("Hora Atual: " + mostra_data.hora);
        txtHora.setFont(new java.awt.Font("Tahoma", 0, 24));

    }//GEN-LAST:event_horasOnTime
    /**
     *
     * @param evt responsável por executar a classe MovimentoVendaView
     */
    private void btnEfetuaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEfetuaVendaActionPerformed
        JFrame form = new MovimentoVendaView();
        form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);
        new MovimentoVendaView();
    }//GEN-LAST:event_btnEfetuaVendaActionPerformed
    /**
     *
     * @param evt responsável por executar a classe ControleAcessoView
     */
    private void itemMenuControleAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuControleAcessoActionPerformed
        if (verificaAcesso(itemMenuControleAcesso.getText(), txtNomeUsuario.getText())) {
            JFrame form = new ControleAcessosView();
            form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            form.setLocationRelativeTo(null);
            form.setResizable(false);
            form.setVisible(true);
            new ControleAcessosView();
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem acesso ao módulo");
        }
    }//GEN-LAST:event_itemMenuControleAcessoActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        JFrame form = new ConsultaView();
        form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);
        new ConsultaView();
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void btnEfetuaOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEfetuaOrcamentoActionPerformed
        JFrame form = new MovimentoOrcamentoView();
        form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);
        new MovimentoOrcamentoView();
    }//GEN-LAST:event_btnEfetuaOrcamentoActionPerformed

    private void itemMenuPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuPedidoActionPerformed
        if (verificaAcesso(itemMenuPedido.getText(), txtNomeUsuario.getText())) {
            JDialog form = new MovimentoPedidoView(this, true);
            form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            form.setLocationRelativeTo(null);
            form.setResizable(false);
            form.setVisible(true);
            new MovimentoPedidoView(this, true);
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem acesso ao módulo");
        }
    }//GEN-LAST:event_itemMenuPedidoActionPerformed

    private void itemMenuEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuEntradaActionPerformed
        if (verificaAcesso(itemMenuEntrada.getText(), txtNomeUsuario.getText())) {
            JDialog form = new MovimentoEntradaView(this, true);
            form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            form.setLocationRelativeTo(null);
            form.setResizable(false);
            form.setVisible(true);
            new MovimentoEntradaView(this, true);
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem acesso ao módulo");
        }
    }//GEN-LAST:event_itemMenuEntradaActionPerformed

    private void itemMenuContaReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuContaReceberActionPerformed
        if (verificaAcesso(itemMenuContaReceber.getText(), txtNomeUsuario.getText())) {
            JFrame form = new ContaReceberView();
            form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            form.setLocationRelativeTo(null);
            form.setResizable(false);
            form.setVisible(true);
            new ContaReceberView();
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem acesso ao módulo");
        }
    }//GEN-LAST:event_itemMenuContaReceberActionPerformed

    private void relatProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatProdutoActionPerformed
        if (verificaAcesso(itemMenuControleAcesso.getText(), txtNomeUsuario.getText())) {
        String[] args = null;
        try {
            ProdutosRelat.main(args);
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }} else {
            JOptionPane.showMessageDialog(null, "Você não tem acesso ao módulo");
        }
    }//GEN-LAST:event_relatProdutoActionPerformed

    private void relatMaisVendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatMaisVendidoActionPerformed
        if (verificaAcesso(itemMenuControleAcesso.getText(), txtNomeUsuario.getText())) {
        String[] args = null;
        try {
            MaisVendidos.main(args);
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem acesso ao módulo");
        }
    }//GEN-LAST:event_relatMaisVendidoActionPerformed

    private void itemMenuPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuPizzaActionPerformed
        if (verificaAcesso(itemMenuControleAcesso.getText(), txtNomeUsuario.getText())) {
        try{
        JFrame form = new GraficoPizza();
            form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            form.setLocationRelativeTo(null);
            form.setResizable(false);
            form.setVisible(true);
            } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }} else {
            JOptionPane.showMessageDialog(null, "Você não tem acesso ao módulo");
        }
    }//GEN-LAST:event_itemMenuPizzaActionPerformed

    private void itemMenuLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuLinhaActionPerformed
        if (verificaAcesso(itemMenuControleAcesso.getText(), txtNomeUsuario.getText())) {
        try{
        JFrame form = new GraficoLinha();
            form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            form.setLocationRelativeTo(null);
            form.setResizable(false);
            form.setVisible(true);
            } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }} else {
            JOptionPane.showMessageDialog(null, "Você não tem acesso ao módulo");
        }
    }//GEN-LAST:event_itemMenuLinhaActionPerformed

    private void itemMenuOndasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuOndasActionPerformed
        if (verificaAcesso(itemMenuControleAcesso.getText(), txtNomeUsuario.getText())) {
        try{
        JFrame form = new GraficoOnda();
            form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            form.setLocationRelativeTo(null);
            form.setResizable(false);
            form.setVisible(true);
            } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }} else {
            JOptionPane.showMessageDialog(null, "Você não tem acesso ao módulo");
        }
    }//GEN-LAST:event_itemMenuOndasActionPerformed

    private void itemMenuBarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuBarrasActionPerformed
        if (verificaAcesso(itemMenuControleAcesso.getText(), txtNomeUsuario.getText())) {
        try{
        JFrame form = new GraficoBarra();
            form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            form.setLocationRelativeTo(null);
            form.setResizable(false);
            form.setVisible(true);
            } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }} else {
            JOptionPane.showMessageDialog(null, "Você não tem acesso ao módulo");
        }
    }//GEN-LAST:event_itemMenuBarrasActionPerformed

    private void itemMenuDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuDiarioActionPerformed
        if (verificaAcesso(itemMenuControleAcesso.getText(), txtNomeUsuario.getText())) {
        String[] args = null;
        try {
            VendasDoDiaValores.main(args);
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }} else {
            JOptionPane.showMessageDialog(null, "Você não tem acesso ao módulo");
        }
    }//GEN-LAST:event_itemMenuDiarioActionPerformed

    private void itemMenuMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuMensalActionPerformed
        if (verificaAcesso(itemMenuControleAcesso.getText(), txtNomeUsuario.getText())) {
        String[] args = null;
        try {
            VendasDoMes.main(args);
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }} else {
            JOptionPane.showMessageDialog(null, "Você não tem acesso ao módulo");
        }
    }//GEN-LAST:event_itemMenuMensalActionPerformed

    private void itemMenuAnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAnualActionPerformed
        if (verificaAcesso(itemMenuControleAcesso.getText(), txtNomeUsuario.getText())) {
        String[] args = null;
        try {
            VendasDoAno.main(args);
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }} else {
            JOptionPane.showMessageDialog(null, "Você não tem acesso ao módulo");
        }
    }//GEN-LAST:event_itemMenuAnualActionPerformed

    private void RelatVendaDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatVendaDiaActionPerformed
        if (verificaAcesso(itemMenuControleAcesso.getText(), txtNomeUsuario.getText())) {
        String[] args = null;
        try {
            VendasDoDia.main(args);
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }} else {
            JOptionPane.showMessageDialog(null, "Você não tem acesso ao módulo");
        }
    }//GEN-LAST:event_RelatVendaDiaActionPerformed

    private void diarioPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diarioPizzaActionPerformed
        if (verificaAcesso(itemMenuControleAcesso.getText(), txtNomeUsuario.getText())) {
        try{
        JFrame form = new VendasMensalPizza();
            form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            form.setLocationRelativeTo(null);
            form.setResizable(false);
            form.setVisible(true);
            } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }} else {
            JOptionPane.showMessageDialog(null, "Você não tem acesso ao módulo");
        }
    }//GEN-LAST:event_diarioPizzaActionPerformed

    private void anualBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anualBarraActionPerformed
       if (verificaAcesso(itemMenuControleAcesso.getText(), txtNomeUsuario.getText())) {
        try{
        JFrame form = new VendasAnuallBarra();
            form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            form.setLocationRelativeTo(null);
            form.setResizable(false);
            form.setVisible(true);
            } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }} else {
            JOptionPane.showMessageDialog(null, "Você não tem acesso ao módulo");
        }
    }//GEN-LAST:event_anualBarraActionPerformed

    private void itemMenuBalancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuBalancoActionPerformed
        if (verificaAcesso(itemMenuControleAcesso.getText(), txtNomeUsuario.getText())) {
        String[] args = null;
        try {
            BalancoAnual.main(args);
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }} else {
            JOptionPane.showMessageDialog(null, "Você não tem acesso ao módulo");
        }
    }//GEN-LAST:event_itemMenuBalancoActionPerformed

    private void itemMenuValorAnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuValorAnualActionPerformed
        if (verificaAcesso(itemMenuControleAcesso.getText(), txtNomeUsuario.getText())) {
        try{
        JFrame form = new VendaAnualComparativo();
            form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            form.setLocationRelativeTo(null);
            form.setResizable(false);
            form.setVisible(true);
            } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }} else {
            JOptionPane.showMessageDialog(null, "Você não tem acesso ao módulo");
        }
    }//GEN-LAST:event_itemMenuValorAnualActionPerformed

    private void itemMenuEpocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuEpocaActionPerformed
        if (verificaAcesso(itemMenuControleAcesso.getText(), txtNomeUsuario.getText())) {
        JFrame form = new ConsultarVendasGrafico();
        form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);} else {
            JOptionPane.showMessageDialog(null, "Você não tem acesso ao módulo");
        }
    }//GEN-LAST:event_itemMenuEpocaActionPerformed

    private void itemMenuEntradaSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuEntradaSaidaActionPerformed
//        JFrame form = new ComparaçãoMensalBarraLinha();
//        form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
//        form.setLocationRelativeTo(null);
//        form.setResizable(false);
//        form.setVisible(true);
        if (verificaAcesso(itemMenuControleAcesso.getText(), txtNomeUsuario.getText())) {
        String[] args = null;
        try {
            ComparaçãoMensalBarraLinha.main(args);
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }} else {
            JOptionPane.showMessageDialog(null, "Você não tem acesso ao módulo");
        }
    }//GEN-LAST:event_itemMenuEntradaSaidaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (verificaAcesso(itemMenuControleAcesso.getText(), txtNomeUsuario.getText())) {
        JFrame form = new ConsultarVendas();
        form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);} else {
            JOptionPane.showMessageDialog(null, "Você não tem acesso ao módulo");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new MenuPrincipalView().setVisible(true);
                txtUsuario.setText(args[0]);
                txtUsuario.setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem RelatVendaDia;
    private javax.swing.JMenuItem anualBarra;
    private javax.swing.JMenuBar barraMenuPrincipal;
    private javax.swing.JButton btnCadastroUsuario;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnEfetuaOrcamento;
    private javax.swing.JButton btnEfetuaVenda;
    private javax.swing.JMenuItem diarioPizza;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JMenuItem itemMenuAnual;
    private javax.swing.JMenuItem itemMenuBairro;
    private javax.swing.JMenuItem itemMenuBalanco;
    private javax.swing.JMenuItem itemMenuBarras;
    private javax.swing.JMenuItem itemMenuCidade;
    private javax.swing.JMenuItem itemMenuCliente;
    private javax.swing.JMenuItem itemMenuContaReceber;
    private javax.swing.JMenuItem itemMenuControleAcesso;
    private javax.swing.JMenuItem itemMenuDiario;
    private javax.swing.JMenuItem itemMenuEntrada;
    private javax.swing.JMenuItem itemMenuEntradaSaida;
    private javax.swing.JMenuItem itemMenuEpoca;
    private javax.swing.JMenuItem itemMenuFornecedor;
    private javax.swing.JMenuItem itemMenuFuncao;
    private javax.swing.JMenuItem itemMenuFuncionario;
    private javax.swing.JMenuItem itemMenuLinha;
    private javax.swing.JMenuItem itemMenuMensal;
    private javax.swing.JMenuItem itemMenuOndas;
    private javax.swing.JMenuItem itemMenuPedido;
    private javax.swing.JMenuItem itemMenuPizza;
    private javax.swing.JMenuItem itemMenuProduto;
    private javax.swing.JMenuItem itemMenuTipoFornecedor;
    private javax.swing.JMenuItem itemMenuTipoPagamento;
    private javax.swing.JMenuItem itemMenuUnidade;
    private javax.swing.JMenuItem itemMenuValorAnual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private java.util.List<br.com.tcc.entity.Funcionario> list;
    private java.util.List<br.com.tcc.entity.Acesso> listAcesso;
    private javax.swing.JMenu menuManutenção;
    private javax.swing.JMenu menuOutros;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenu menuSair;
    private javax.swing.JPanel pnlAcoes;
    private javax.swing.JPanel pnlInformacao;
    private java.util.List<br.com.tcc.entity.Produto> produtoList;
    private javax.persistence.Query produtoQuery;
    private javax.persistence.Query query;
    private javax.persistence.Query queryAcesso;
    private javax.swing.JMenuItem relatMaisVendido;
    private javax.swing.JMenuItem relatProduto;
    private javax.swing.JLabel txtData;
    private javax.swing.JLabel txtHora;
    private javax.swing.JLabel txtLogou;
    private javax.swing.JLabel txtNomeUsuario;
    private javax.swing.JLabel txtSejaBemVindo;
    private javax.swing.JLabel txtSemana;
    private static javax.swing.JLabel txtUsuario;
    private java.util.List<br.com.tcc.entity.Vendadetalhe> vendaDetalheList;
    private javax.persistence.Query vendaDetalheQuery;
    // End of variables declaration//GEN-END:variables
    /**
     * Método de verificação de acesso
     *
     * @param nomeMenu verifica se o usuário logado tem acesso ao menu
     * @param nomeUsuario verifica se o usuário logado tem acesso ao menu
     * @return tem como retorno true ou false
     */
    private boolean verificaAcesso(String nomeMenu, String nomeUsuario) {
        queryAcesso = entityManager.createNamedQuery("Acesso.verifiqueAcesso");
        queryAcesso.setParameter("idFuncionario", Integer.parseInt(txtUsuario.getText()));
        queryAcesso.setParameter("modelo", nomeMenu);
        List<Acesso> data = queryAcesso.getResultList();
        if (data.size() > 0) {
            return true;
        } else {
            return false;
        }
    }
}
